
name: Apply Patch and Create PR

on:
  workflow_dispatch:
    inputs:
      patchContent:
        description: 'Git patch content'
        required: true

jobs:
  apply-patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history


    - name: Apply patch
      run: echo "${{ github.event.inputs.patchContent }}" | base64 -d | git apply --allow-empty


    - name: Display diff
      run: |
        git diff


    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # is this needed?
        git add .
        git commit -m "Apply patch"


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Patch Applied
        body: Patch has been applied and this PR is created for review.
